// Source/RICS/UI/TabDrawer_Kick.cs
// Copyright (c) Captolamia
// This file is part of RICS (Rimworld Interactive Chat Services).
// 
// CAP Chat Interactive is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// CAP Chat Interactive is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with CAP Chat Interactive. If not, see <https://www.gnu.org/licenses/>.
// A dialog window for configuring Chat Interactive settings with multiple tabs
//
// Simple, streamer-friendly Kick.com settings tab.
// Modeled on TabDrawer_YouTube (clean) with secure token handling like Twitch.
// Uses official OAuth 2.1 (Client ID + Secret) — Access Token is auto-generated by KickService.

using CAP_ChatInteractive;
using RimWorld;
using System.Text;
using UnityEngine;
using Verse;
using ColorLibrary = CAP_ChatInteractive.ColorLibrary;

namespace _CAP__Chat_Interactive
{
    public static class TabDrawer_Kick
    {
        private static Vector2 _scrollPosition = Vector2.zero;

        public static void Draw(Rect region)
        {
            var settings = CAPChatInteractiveMod.Instance.Settings.KickSettings;
            var view = new Rect(0f, 0f, region.width - 16f, 620f); // compact height

            Widgets.BeginScrollView(region, ref _scrollPosition, view);
            var listing = new Listing_Standard();
            listing.Begin(view);

            // === Header ===
            Text.Font = GameFont.Medium;
            GUI.color = ColorLibrary.HeaderAccent;
            listing.Label("RICS.Kick.KickIntegrationHeader".Translate());
            GUI.color = Color.white;
            Text.Font = GameFont.Small;

            listing.Gap(8f);
            // Enable toggle
            listing.CheckboxLabeled("RICS.Kick.EnableIntegrationLabel".Translate(), ref settings.Enabled);
            TooltipHandler.TipRegion(listing.GetRect(0f), "RICS.Kick.EnableIntegrationTooltip".Translate());

            // BIG WARNING — prevents streamers from connecting when not live
            listing.Gap(8f);
            GUI.color = Color.yellow;
            // listing.Label("⚠️ You must be LIVE streaming on Kick.com to connect!");
            listing.Label("RICS.Kick.LiveWarning".Translate());
            GUI.color = Color.white;
            listing.Gap(4f);
            // listing.Label("Kick requires an active stream for chatroom access.");
            listing.Label("RICS.Kick.ReqActive".Translate());
            listing.Gap(12f);

            // === Channel Slug ===
            Text.Font = GameFont.Medium;
            GUI.color = ColorLibrary.SubHeader;
            listing.Label("RICS.Kick.ChannelInformationHeader".Translate());
            Text.Font = GameFont.Small;
            GUI.color = Color.white;
            listing.GapLine(6f);

            Rect channelLabelRect = listing.GetRect(24f);
            Widgets.Label(channelLabelRect, "RICS.Kick.ChannelSlugLabel".Translate());
            TooltipHandler.TipRegion(channelLabelRect, "RICS.Kick.ChannelSlugTooltip".Translate());

            Rect channelFieldRect = listing.GetRect(30f);
            settings.ChannelName = Widgets.TextField(channelFieldRect, settings.ChannelName);
            TooltipHandler.TipRegion(channelFieldRect, "RICS.Kick.ChannelSlugFieldTooltip".Translate());

            listing.Gap(16f);

            // === OAuth Credentials (secure) ===
            Text.Font = GameFont.Medium;
            GUI.color = ColorLibrary.SubHeader;
            listing.Label("RICS.Kick.OAuthCredentialsHeader".Translate());
            Text.Font = GameFont.Small;
            GUI.color = Color.white;
            listing.GapLine(6f);

            // Client ID
            Rect clientIdLabelRect = listing.GetRect(24f);
            Widgets.Label(clientIdLabelRect, "RICS.Kick.ClientIdLabel".Translate());
            TooltipHandler.TipRegion(clientIdLabelRect, "RICS.Kick.ClientIdTooltip".Translate());
            Rect clientIdFieldRect = listing.GetRect(30f);
            settings.ClientId = Widgets.TextField(clientIdFieldRect, settings.ClientId);

            listing.Gap(8f);

            // Client Secret (masked + paste)
            Rect secretLabelRect = listing.GetRect(24f);
            Widgets.Label(secretLabelRect, "RICS.Kick.ClientSecretLabel".Translate());
            TooltipHandler.TipRegion(secretLabelRect, "RICS.Kick.ClientSecretTooltip".Translate());

            Rect secretFieldRect = listing.GetRect(30f);
            string secretDisplay = string.IsNullOrEmpty(settings.ClientSecret)
                ? "RICS.Kick.ClientSecretPlaceholder".Translate()
                : "••••••••••••••••";
            Widgets.TextField(secretFieldRect, secretDisplay);

            Rect pasteSecretRect = listing.GetRect(30f);
            if (Widgets.ButtonText(pasteSecretRect, "RICS.Kick.PasteSecretButton".Translate()))
            {
                string clipboard = GUIUtility.systemCopyBuffer?.Trim();
                if (!string.IsNullOrEmpty(clipboard))
                {
                    settings.ClientSecret = clipboard;
                    Messages.Message("RICS.Kick.SecretPastedSuccess".Translate(), MessageTypeDefOf.PositiveEvent);
                }
                else
                {
                    Messages.Message("RICS.Kick.ClipboardEmpty".Translate(), MessageTypeDefOf.NegativeEvent);
                }
            }
            TooltipHandler.TipRegion(pasteSecretRect, "RICS.Kick.PasteSecretTooltip".Translate());

            listing.Gap(16f);

            // === Connection Settings ===
            Text.Font = GameFont.Medium;
            GUI.color = ColorLibrary.SubHeader;
            listing.Label("RICS.Kick.ConnectionSettingsHeader".Translate());
            Text.Font = GameFont.Small;
            GUI.color = Color.white;
            listing.GapLine(6f);

            listing.CheckboxLabeled("RICS.Kick.AutoConnectLabel".Translate(), ref settings.AutoConnect);
            TooltipHandler.TipRegion(listing.GetRect(0f), "RICS.Kick.AutoConnectTooltip".Translate());

            listing.Gap(12f);

            string status = "RICS.Kick.Status".Translate(
                ColorLibrary.Colorize(settings.IsConnected ? "RICS.Kick.Connected".Translate() : "RICS.Kick.Disconnected".Translate(),
                    settings.IsConnected ? Color.green : Color.red)
            );
            listing.Label(status);

            bool canConnect = !string.IsNullOrEmpty(settings.ChannelName) &&
                              !string.IsNullOrEmpty(settings.ClientId) &&
                              !string.IsNullOrEmpty(settings.ClientSecret);

            if (canConnect)
            {
                if (listing.ButtonText("RICS.Kick.ConnectButton".Translate()))
                {
                    CAPChatInteractiveMod.Instance.KickService.Connect();
                    Messages.Message("RICS.Kick.ConnectingMessage".Translate(), MessageTypeDefOf.SilentInput);
                }
            }
            else
            {
                GUI.color = Color.gray;
                listing.ButtonText("RICS.Kick.CannotConnectButton".Translate());
                GUI.color = Color.white;
                TooltipHandler.TipRegion(listing.GetRect(0f), "RICS.Kick.CannotConnectTooltip".Translate());
            }
            // Quick tip
            listing.Gap(20f);
            GUI.color = ColorLibrary.MutedText;
            listing.Label("RICS.Kick.QuickTip".Translate());
            GUI.color = Color.white;

            listing.End();
            Widgets.EndScrollView();
        }
    }
}